import Navbar from "@/components/Navbar";
import { TasksProvider } from "@/context/TasksContext";
import { Toaster } from "./Toaster";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <TasksProvider>
          {children}
          <Toaster />
        </TasksProvider>
      </body>
    </html>
  );
}
